version: '3.9'

networks:
  backendDisrupt:
    driver: bridge

services:
  database:
    image: postgres
    container_name: database_disrupt
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=disrupt
      - POSTGRES_PASSWORD=disrupt
      - POSTGRES_DB=disrupt
    volumes:
      - pgdata:/data/postgres - postgres
    networks:
      - backendDisrupt

  app:
    build: .
    container_name: disrupt
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
    networks:
      - backendDisrupt

  redis:
    image: redis:latest
    container_name: redis_disrupt
    restart: always
    ports:
      - 6379:6379
    networks:
      - backendDisrupt

volumes:
  pgdata:
    driver: local