version: '3.9'

networks:
  backendDisrupt:
    driver: bridge

services:
  database:
    image: postgres
    container_name: database_disrupt
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=disrupt
      - POSTGRES_PASSWORD=disrupt
      - POSTGRES_DB=disrupt
    volumes:
      - pgdata:/data/postgres
    networks:
      - backendDisrupt

  mongo:
    image: mongo
    container_name: mongo_disrupt
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=disrupt
      - MONGO_INITDB_ROOT_PASSWORD=disrupt
    volumes:
      - mongo_data:/data/db
    networks:
      - backendDisrupt
  # nextjs:
  #   image: disruptfront:latest # Caminho para o Next.js dentro do app_principal
  #   depends_on:
  #     - app
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - backendDisrupt
  #   environment:
  #     - DISPLAY=:0  # Configuração para apps gráficos no Electron
  #   volumes:
  #     - .:/nextjs
  #     - /nextjs/node_modules
  #     - /nextjs/.next
  #     - /tmp/.X11-unix:/tmp/.X11-unix  # Permite exibição gráfica do Electron
  app:
    build: .
    container_name: disrupt
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
      - mongo
    depends_on:
      - database
      - mongo
    networks:
      - backendDisrupt

  redis:
    image: redis:latest
    container_name: redis_disrupt
    restart: always
    ports:
      - 6379:6379
    networks:
      - backendDisrupt

volumes:
  pgdata:
    driver: local
  mongo_data:
    driver: local
